# Generated by Django 3.0.7 on 2026-01-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20260105_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
