# Generated by Django 3.0.7 on 2026-01-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20260106_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
