# Generated by Django 3.0.7 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
